### ISSUE TITLE
unable to load the model using demo.py

### ISSUE THREAD

**Issue by shanchaoL** [infly-ai/INF-MLLM#1]
Hi, thank you for releasing the model. However, when I try to follow your demo code, it seems that I could not load the model from huggingface using automodel.from_pretrained().

Here is the error message:
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.llama.configuration_llama.LlamaConfig'> and you passed <class 'transformers_modules.mightyzau.InfMLLM_7B_Chat.d3f0fe9071ccdd8dacb87b35af251a18ed9e7438.configuration_infmllm_chat.InfMLLMChatConfig'>. Fix one of those so they match!

Do you know how to solve this problem? Thanks.

**Comment by mightyzau** [comment]
It is recommended to download the infmllm_7b_chat (https://huggingface.co/mightyzau/InfMLLM_7B_Chat) model from Huggingface in advance, and then load the model locally.
